services:
  ollama:
    image: ollama/ollama
    container_name: ollamone
    ports:
      - "11434:11434"
    shm_size: '2gb' # Il fix per non far bloccare l'OCR alla terza pagina
    volumes:
      - ollama_vecchio:/root/.ollama
    # AGGIUNTA FONDAMENTALE: Passa la GPU NVIDIA a Docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: "no"

  postgres_vector:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector
    hostname: d28097d83439
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vector_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD="RAGatha42"
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "C:\\Users\\federico.mantoni\\Documents\\PostgreSQL/postgres_data:/var/lib/postgresql/data"
    restart: "no"

# FIX INDENTAZIONE: Adesso la struttura globale è corretta
volumes:
  ollama_vecchio:
    external: true
    name: ollama